### ISSUE TITLE
Uno Compatibility

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/Uno.Xaml-Controls-Gallery#4]
**Phase 1**
- [x] NavigationView selection is somethings providing an incorrect selected item (generally the last)
- [x] Sample text is not available
- [x] Some Images in top NavigationView are incorrect
- [x] FontIcon default size is incorrect
- [x] GridView SelectionMode combobox is not appearing
- [x] GridView item selection count is not working
- [x] GridView ItemTemplate changes are not working
- [x] ListView samples are not showing any content
- [x] Custom button is incorrect
- [x] Flyout positioning and background is incorrect
- [x] GridView padding is not working properly (main list items are too large, wasm only)
- [x] ComboBoxes don't show the popup
- [x] AutoSuggestBox both samples are not displaying search content
- [ ] TextBlock glyph is trimmed in navigation view
- [x] Settings is not showing About text
- [x] Settings is not showing dependencies
- [x] Settings is not showing the disclaimer

**Phase 2**
- [ ] ListView Image list stretches images (wasm)
- [ ] NavigationView layout cycle wasm issue
- [ ] ToggleSwitch on/off text is not present
- [ ] ProgressBar indeterminate is not available
- [ ] Default checkbox three option 2 is not checked
- [ ] Canvas Slider header is not showing up
- [ ] Canvas Z-Index is not working
- [ ] NavigationView DataBinding sample not working
- [ ] ScrollViewer re-test when ComboBox will work
- [ ] Motion Easing Functions is not working
- [ ] SplitView default size is incorrect
- ~~Grid vertical slider value is inverted~~
- [ ] Vertical Slider is incorrect (invalid range?)

**Phase 3**

- [ ] Passwordbox custom character is not available
- [ ] EasingFunctions do not work
- [ ] RadioButton: Disabled scrollviewer should not show the slider
- [ ] ToggleButton "Disable toggle" is not placed properly
- [ ] TimePicker is partially implemented?
- [ ] SplitView left mode is not working
- [ ] WebView is not working
- [ ] GridView Item hover is not showing
- [ ] AppBarButton BitmapIcon is not working
- [ ] AppBarButton PathIcon is not working
- [ ] AppBarButton FontIcon size is incorrect
- [ ] AppBarSeparator ScrollViewer size is incorrect
- [ ] NavigationView Title (Sample Page 1) is not visible
- [ ] NavigationView Top samples need to be disabled (not supported yet)
- [ ] ProgressBar RepeatButton is not working
- [ ] ProgressRing is not working
- [ ] Image nine grid is not working
